# AI Agents Integration Lab Configuration
#
# This file contains configuration for the integration lab environment,
# including external agent settings, API connectors, and quality standards.

[integration_lab]
name = "AI Agents Integration Lab"
version = "1.0.0"
environment = "development"
debug = true

[quality_standards]
# Minimum test pass rate for agent integration
min_test_pass_rate = 80

# Maximum response time in seconds
max_response_time = 5

# Maximum memory usage in MB
max_memory_usage = 512

# Minimum documentation coverage
min_documentation_coverage = 85

[owl_integration]
# OWL Framework integration settings
enabled = true
fallback_mode = true
model_type = "gpt-4o-mini"
max_iterations = 10
timeout = 30

[external_agents]
# Configuration for external agent frameworks

[external_agents.autogpt]
enabled = false
priority = "high"
status = "research"
repository = "https://github.com/Significant-Gravitas/AutoGPT"
documentation = "https://docs.autogpt.net/"

[external_agents.langchain]
enabled = false
priority = "high" 
status = "research"
repository = "https://github.com/langchain-ai/langchain"
documentation = "https://python.langchain.com/"

[external_agents.crewai]
enabled = false
priority = "medium"
status = "research"
repository = "https://github.com/joaomdmoura/crewAI"
documentation = "https://docs.crewai.com/"

[external_agents.metagpt]
enabled = false
priority = "medium"
status = "research"
repository = "https://github.com/geekan/MetaGPT"
documentation = "https://docs.deepwisdom.ai/"

[api_connectors]
# API connector configuration

[api_connectors.openai]
enabled = true
api_key_env = "OPENAI_API_KEY"
rate_limit = 3500
timeout = 30
retry_count = 3

[api_connectors.anthropic]
enabled = false
api_key_env = "ANTHROPIC_API_KEY"
rate_limit = 1000
timeout = 30
retry_count = 3

[api_connectors.stripe]
enabled = true
api_key_env = "STRIPE_SECRET_KEY"
webhook_secret_env = "STRIPE_WEBHOOK_SECRET"
rate_limit = 100
timeout = 30

[marketplace_api]
# Marketplace API configuration
enabled = true
base_url = "http://localhost:8001/api/v1"
timeout = 30
rate_limit = 1000

[marketplace_api.authentication]
method = "jwt"
token_expiry = 3600
refresh_enabled = true

[marketplace_api.categories]
website_development = ["frontend_design", "backend_development", "ecommerce", "seo"]
business_intelligence = ["analytics", "marketing", "customer_support", "lead_generation"]  
content_creation = ["copywriting", "image_generation", "video_creation", "social_media"]
productivity = ["project_management", "calendar", "email_automation", "document_processing"]

[testing]
# Testing configuration
framework = "pytest"
coverage_minimum = 80
parallel_execution = true
timeout = 300

[testing.categories]
unit_tests = true
integration_tests = true
performance_tests = true
security_tests = true
compatibility_tests = true

[logging]
# Logging configuration
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "integration_lab.log"
max_size = "10MB"
backup_count = 5

[docker]
# Docker configuration
image = "multi-ai-agents-integrated"
container_name = "multi-ai-agents-integrated"
port_mapping = "8002:8000"
volume_mapping = "./:/app"
network = "ai-agents-network"

[security]
# Security configuration
api_key_encryption = true
secure_credential_storage = true
audit_logging = true
rate_limiting = true
input_validation = true

[monitoring]
# Monitoring and metrics
enabled = true
metrics_endpoint = "/metrics"
health_check_endpoint = "/health"
performance_tracking = true
error_tracking = true

[development]
# Development environment settings
hot_reload = true
debug_mode = true
verbose_logging = true
test_data_generation = true
mock_external_apis = false
